# Домашня робота №2

## 1 Пароль
Напишіть програму (функцію) для генерування випадкового пароля з такими обмеженнями:
- пароль складається з рівно $10$ символів
- пароль містить хоча б одну маленьку латинську літеру [a-z]
- пароль містить хоча б одну велику латинську літеру [A-Z]
- пароль містить хоча б одну цифру [0-9]
- пароль містить хоча б один спеціальний символ [~!@#$%^&*()-_+=\/{}[].,?<>:;]

In [3]:
# Місце для Вашого коду
import numpy as np

a = [1,2,3,4,5,6,7,8,9,0]
size = 1
probs = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

[1]


## 2 Герби в ряд
Реалізуйте функцію для обчислення емпіричної та теоретичної імовірностей випадіння $k$ гербів (HEADS) підряд у серії з $n$ підкидань чесної монетки. Підрахуйте відповідні ймовірності для таких параметрів:
- $k = 2, n = 10, 50, 100, 500, 1000, 5000, 10000$
- $k = 3, n = 10, 50, 100, 500, 1000, 5000, 10000$

**Зауваження.** Нехай $k = 2, n = 10$ та маємо таку послідовність результатів підкидання монети: $\{ H, T, H, H, H, H, T, T, H, T \}$. Тоді матимемо $3$ випадки випадіння двох гербів підряд та емпіричну ймовірність такої події $1/3$.

In [4]:
# Місце для Вашого коду
import numpy as np

a = [1,2,3,4,5,6,7,8,9,0]
m = 4
n = 6
probs = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
replace = True
print(np.random.choice(a, size=(m,n), replace=replace, p=probs))


[[7 9 5 1 4 3]
 [8 0 9 4 4 1]
 [0 0 5 9 1 4]
 [3 8 9 3 2 4]]


## 3 Найбільше число
Реалізуйте функцію підрахунку точної (теоретичної) імовірності того, що максимальне число після $n$ кидків звичайного грального кубика дорівнює $x\_max$, для таких параметрів:
- $n = 3, x\_max = 6$
- $n = 2, x\_max = 3$
- $n = 3, x\_max = 5$

Тобто, якщо $X_i, i = 1, \ldots, n$, - число на $i$-му кидку кубика, а $X = \max\limits_{1 \leq i \leq n} X_i$, то потрібно знайти ймовірність $\textbf{P} \left( X = x\_max \right)$.

Підрахуйте також емпіричні ймовірності відповідних подій у випадку $10000$ симуляцій.

**Зауваження.** Якщо введені параметри не мають сенсу, то повертати $0$.
Тобто, якщо вводиться $x\_max < 1$ або $x\_max > 6$.

In [5]:
# Місце для Вашого коду
size = (3,4)

print(np.random.sample(size=size))


[[0.53650246 0.15186682 0.13089435 0.71604002]
 [0.5528914  0.80974942 0.54735092 0.43020095]
 [0.20448029 0.64944046 0.33739768 0.42908901]]


## 4 Сума чисел
Реалізуйте функцію підрахунку точної (теоретичної) імовірності того, що сума чисел після $n$ кидків звичайного грального кубика дорівнює $s$, для таких параметрів:
- $n = 3, s = 13$
- $n = 2, s = 5$
- $n = 3, s = 7$

Тобто, якщо $X_i, i = 1, \ldots, n$, - число на $i$-му кидку кубика, а $X = \sum\limits_{i = 1}^{n} X_i$, то потрібно знайти ймовірність $\textbf{P} \left( X = s \right)$.

Підрахуйте також емпіричні ймовірності відповідних подій у випадку $10000$ симуляцій.

**Зауваження.** Якщо введені параметри не мають сенсу, то повертати $0$.
Наприклад, якщо при $n = 3$ вводиться $s < 3$ або $s > 18$.

In [10]:
# Місце для Вашого коду
a = 3
b = 5
size = 10

print((b-a)*np.random.sample(size=size) + a)

[4.96757162 3.97093248 4.73674734 4.59139723 4.92967634 4.85698424
 4.26290743 3.49144148 4.95970126 3.24562421]


In [12]:
M = np.arange(20).reshape((4, 5))
print(M)
np.random.shuffle(M)
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  1  2  3  4]]


In [13]:

p=0.5
n=100
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

['T' 'T' 'H' 'T' 'T' 'T' 'T' 'T' 'T' 'H' 'H' 'H' 'T' 'T' 'T' 'H' 'T' 'H'
 'T' 'T' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'T' 'T' 'H' 'T' 'T' 'T' 'T' 'T'
 'H' 'H' 'H' 'H' 'T' 'T' 'H' 'T' 'H' 'H' 'H' 'T' 'T' 'H' 'T' 'T' 'T' 'H'
 'T' 'H' 'H' 'T' 'H' 'H' 'T' 'T' 'T' 'T' 'T' 'H' 'T' 'T' 'T' 'H' 'T' 'H'
 'H' 'H' 'H' 'T' 'T' 'H' 'T' 'H' 'T' 'H' 'H' 'H' 'T' 'T' 'H' 'H' 'H' 'T'
 'T' 'H' 'T' 'H' 'T' 'T' 'H' 'T' 'T' 'T']
46 heads and 54 tails


In [23]:
np.random.seed(42)
m = []
e = ["H","T"]
h = 0
t = 0
a = np.random.randint(10, size=100)
for i in a:
    if i%2 == 0:
        h += 1
        m.append(e[0])
    else:
        t += 1
        m.append(e[1])
print("{} heads and {} tails".format(h,t))


49 heads and 51 tails


In [31]:
a = 0
b = 100
size = 100
e = ["H","T"]
h = 0
t = 0
m = []
r = (b-a)*np.random.sample(size=size) + a
for i in r:
    if i<50:
        h += 1
        m.append(e[0])
    else:
        t += 1
        m.append(e[1])
print("{} heads and {} tails".format(h,t))

53 heads and 47 tails


In [6]:
m = [10,50,100,250,500,1000,2500,5000,10000]
p=0.5
for n in m:
    tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
    heads = list(tosses).count("H")
    tails = list(tosses).count("T")
    r = heads / n
    print("result {}".format(r))

result 0.6
result 0.66
result 0.6
result 0.452
result 0.506
result 0.481
result 0.4952
result 0.5118
result 0.5017


In [8]:
import numpy as np

m = [10,50,100,250,500,1000,2500,5000,10000]
e = [1,2,3,4,5,6]
r = {}
p=0.5
for n in m:
    tosses=np.random.choice(e,p=[1/6,1/6,1/6,1/6,1/6,1/6], size=n)
for i in e:
    a = list(tosses).count(i)
    result = a/n
    r[i] = result
print("result {}".format(r))

result {1: 0.1638, 2: 0.165, 3: 0.164, 4: 0.1734, 5: 0.1681, 6: 0.1657}


In [18]:
import numpy as np

Ranks = ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K')
Suits = ('♢', '♠', '♣', '♡')
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
m = [10,50,100,250,500,1000,2500,5000,10000]
p = []
e = []
for i in range(52):
    p.append(1/52)
    e.append(i)
r = {}
for n in m:
    k = 0
    tosses = np.random.choice(e,p=p, size=n)
    t = []
    for i in tosses:
        t.append(Cards[i])
    for i in t:
        try:
            if int(i[0])%2:
                k += 1
        except:
            pass
        r[n] = k/52
print("result {}".format(r))

result {10: 0.11538461538461539, 50: 0.38461538461538464, 100: 0.7115384615384616, 250: 1.8269230769230769, 500: 3.5961538461538463, 1000: 7.346153846153846, 2500: 19.28846153846154, 5000: 37.17307692307692, 10000: 73.98076923076923}


In [35]:
Ranks = ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K')
Suits = ('♢', '♠', '♣', '♡')
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
np.random.shuffle(Cards)
k = 0 
d = [[],[],[],[]]
for i in Cards:
    if i[1] == '♢':
        d[0].append(i)
    elif i[1] == '♠':
        d[1].append(i)
    elif i[1] == '♣':
        d[2].append(i)
    elif i[1] == '♡':
        d[3].append(i)

r = [[],[],[],[]]
for i in range(13):
    r[k].append([d[0][i],d[1][i],d[2][i],d[3][i]])
    k += 1
    if k == 4:
        k = 0
print(r)

[[[('10', '♢'), ('9', '♠'), ('3', '♣'), ('7', '♡')], [('K', '♢'), ('Q', '♠'), ('1', '♣'), ('2', '♡')], [('6', '♢'), ('3', '♠'), ('2', '♣'), ('4', '♡')], [('2', '♢'), ('6', '♠'), ('6', '♣'), ('10', '♡')]], [[('9', '♢'), ('2', '♠'), ('8', '♣'), ('5', '♡')], [('1', '♢'), ('7', '♠'), ('Q', '♣'), ('9', '♡')], [('3', '♢'), ('4', '♠'), ('10', '♣'), ('K', '♡')]], [[('4', '♢'), ('J', '♠'), ('4', '♣'), ('Q', '♡')], [('8', '♢'), ('5', '♠'), ('5', '♣'), ('6', '♡')], [('J', '♢'), ('K', '♠'), ('9', '♣'), ('8', '♡')]], [[('7', '♢'), ('10', '♠'), ('K', '♣'), ('1', '♡')], [('Q', '♢'), ('8', '♠'), ('7', '♣'), ('3', '♡')], [('5', '♢'), ('1', '♠'), ('J', '♣'), ('J', '♡')]]]
